name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 'latest'

      - name: Build WebAssembly
        run: |
          make -f Makefile.wasm all

      - name: Create deployment directory
        run: |
          mkdir -p deploy
          cp -r build/wasm/* deploy/
          # Create index.html that redirects to the app with test file
          cat > deploy/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <meta http-equiv="refresh" content="0;url=RobusText.html?file=/testdata/simple_combining.txt">
            <title>RobusText Editor</title>
          </head>
          <body>
            <p>Loading RobusText Editor...</p>
            <p>If not redirected, <a href="RobusText.html?file=/testdata/simple_combining.txt">click here</a>.</p>
          </body>
          </html>
          EOF

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: deploy

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
